version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=assetflow
      - POSTGRES_PASSWORD=assetflow
      - POSTGRES_DBNAME=assetflowdb
    
    volumes:
      - assetflowvolume:/var/lib/postgresql/data  # Caminho correto para o PostgreSQL

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  assetflowvolume:  
  pgadmin_data: